2025-05-26 13:51:06,688 [INFO] [root] Logging configurado. Archivo de log: logs\2025-05-26\2025-05-26_13-51-06.log
2025-05-26 13:51:06,689 [INFO] [main] Inicio del programa principal
2025-05-26 13:51:06,692 [INFO] [main] Inicio del proceso de evaluación del chatbot.
2025-05-26 13:51:06,695 [ERROR] [main] Error en la ejecución principal: 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "C:\Users\CASTILLOEMILYGABRIEL\OneDrive - TK Elevator\Documentos\chatbot_evaluation\app\main.py", line 239, in main
    result = evaluate_combination(config)
  File "C:\Users\CASTILLOEMILYGABRIEL\OneDrive - TK Elevator\Documentos\chatbot_evaluation\app\main.py", line 124, in evaluate_combination
    config_score = evaluate_label(label, questions, config)
  File "C:\Users\CASTILLOEMILYGABRIEL\OneDrive - TK Elevator\Documentos\chatbot_evaluation\app\main.py", line 138, in evaluate_label
    for question in questions.items():
                    ^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
